### ISSUE TITLE
Feature proposal (random index)

### ISSUE THREAD

**Issue by RinatValiullov** [carolinaknoll/carolinaknoll.github.io#3]
Hi, Carolina! Cool personal website. I like it :raising_hand:

You can also make a random index number with help of this:
```js
let randomIndex = ~~(Math.random() * presentationTopicsFirst.length);
```
May come in handy someday.

https://github.com/carolinaknoll/carolinaknoll.github.io/blob/3f945df0d64f82c753f771d01addbbef43277820/js/scripts.js#L31

**Comment by carolinaknoll** [comment]
Hi, Rinat! 👋 

Thanks for your feedback, it means a lot! 😄 

About your idea, it is really nice! I haven't thought of it this way when I was developing this part of the website.

I have some other projects going on right now, but I will put your idea into practice soon in the following weeks.

In any case, If you would like, you can create a pull request with it during Hacktoberfest. :octocat: 

Thank you! 😄

**Comment by RinatValiullov** [comment]
@carolinaknoll 

Cool! Ok, will add `PR`.
